
#define HOME_PAGE_ADDRESS 0x0000
#define PAGE_1_ADDRESS 0x01E0 // screen size is cols x rows (16 x 30 = 480 [0x1e])
#define PAGE_2_ADDRESS 0x03C0
#define PAGE_3_ADDRESS 0x05A0

#define MODE_HOME_PAGE_MENU_VIEW 0
#define MODE_PAGE_2_DATATABLE_VIEW 1
#define MODE_PAGE_3_OPTIONS_VIEW 2
#define MODE_PAGE_1_GREENHOUSE_VIEW 4

#define MODE_TEMP_LOW_EDIT 5
#define MODE_TEMP_HIGH_EDIT 6
#define MODE_DATE_EDIT 7
#define MODE_CLOCK_EDIT 8

#define HOME_BUTTON 10
#define RETURN_BUTTON 12
